{{- if .Values.database.enabledPostgre -}}
apiVersion: v1
data:
  CreateDB.sql: |-
    CREATE TABLE text (
        id serial PRIMARY KEY,
        text VARCHAR ( 100 ) UNIQUE NOT NULL
    );
kind: ConfigMap
metadata:
  name: pg-init-script
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: postgres
        image: postgres
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: sqlscript
          mountPath: /docker-entrypoint-initdb.d
        - name: db
          mountPath: /var/lib/postgresql/18/docker
        env:
          - name: POSTGRES_USER
            value: "{{ .Values.postgre.adminUser }}"
          - name: POSTGRES_PASSWORD
            value: "{{ .Values.postgre.adminPassword }}"
      volumes:
        - name: sqlscript
          configMap:
            name: pg-init-script
  volumeClaimTemplates:
  - metadata:
      name: db  # PVC模板名称
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "nfs-client"  # 存储类的名称
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: pg-service
  labels:
    app: database
spec:
  clusterIP: None
  selector:
    app: database
  ports:
  - port: 5432
{{- end }}
